
FIND_PATH (SQLITE_INCLUDE_DIR sqlite3.h )

FIND_LIBRARY(SQLITE_LIBRARY
	NAMES sqlite sqlite3
	DOC "The name of the sqlite library"
)

IF(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY)
	SET(SQLITE_FOUND TRUE)
ENDIF()
