
FIND_PATH (ORACLE_INCLUDE_DIR occi.h "${ORACLE_OCI_INC_DIR}" )

FIND_LIBRARY(ORACLE_OCI_LIBRARY NAMES oci PATHS "$ENV{OCI_LIB_DIR}" )

FIND_LIBRARY(ORACLE_OCCI_LIBRARY_DEBUG NAMES occid PATHS "$ENV{OCCI_LIB_DIR}" )
FIND_LIBRARY(ORACLE_OCCI_LIBRARY_RELEASE NAMES occi PATHS "$ENV{OCCI_LIB_DIR}"  )


HAF_SET_DEBUG_RELEASE_LIBRARY ( ORACLE_OCCI_LIBRARY ORACLE_OCCI_LIBRARY_DEBUG ORACLE_OCCI_LIBRARY_RELEASE )

SET(ORACLE_LIBRARIES ${ORACLE_OCCI_LIBRARY} )

IF ( ORACLE_OCI_LIBRARY )
	SET(ORACLE_LIBRARIES ${ORACLE_OCI_LIBRARY} ${ORACLE_LIBRARIES} )
ENDIF()

IF(ORACLE_INCLUDE_DIR AND ORACLE_LIBRARIES)
	SET(ORACLE_FOUND TRUE)
ENDIF()
